'use client';

import React from 'react';
import { BarChart3, Download, FileText, Sparkles } from 'lucide-react';
import { GlowCard } from '@/components/ui/glow-card';
import { toast } from 'sonner';

const REPORTS = [
  {
    id: '1',
    title: 'Q2 Executive Summary & Board Deck',
    date: 'Generated 2 hours ago',
    department: 'CEO & All Agents',
    pages: '18 Pages',
    type: 'PDF',
  },
  {
    id: '2',
    title: 'Monthly Financial Audit & Runway Projection',
    date: 'Generated yesterday',
    department: 'Finance',
    pages: '6 Pages',
    type: 'CSV & PDF',
  },
  {
    id: '3',
    title: 'Talent Acquisition & Compensation Benchmarks',
    date: 'Generated 3 days ago',
    department: 'Talent',
    pages: '8 Pages',
    type: 'PDF',
  },
  {
    id: '4',
    title: 'Product-Led Growth & GTM Conversion Audit',
    date: 'Generated 5 days ago',
    department: 'Growth',
    pages: '12 Pages',
    type: 'PDF',
  },
];

export default function ReportsPage() {
  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/10 pb-6">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold mb-3">
            <BarChart3 size={14} />
            Cross-Department Intelligence Reports
          </div>
          <h1 className="text-3xl font-bold text-white tracking-tight">
            Executive Reports & Audits
          </h1>
          <p className="text-slate-400 text-sm mt-1">
            Automated PDF & CSV intelligence exports generated by CEO Planner and executive agents.
          </p>
        </div>

        <button
          onClick={() => {
            toast.success('CEO Planner synthesizing Q3 Board Briefing Report...', { icon: '📊' });
          }}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold transition-all shadow-lg shadow-indigo-500/20 self-start md:self-auto"
        >
          <Sparkles size={14} />
          Generate Complete Startup Audit
        </button>
      </div>

      {/* Reports List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {REPORTS.map((report) => (
          <GlowCard key={report.id} className="hover:border-indigo-500/40 transition-all">
            <div className="flex items-start justify-between mb-4">
              <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0">
                <FileText size={20} />
              </div>
              <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-white/5 border border-white/10 text-slate-300">
                {report.type}
              </span>
            </div>

            <h3 className="text-base font-bold text-white mb-1">{report.title}</h3>
            <p className="text-xs text-slate-400 mb-4">
              {report.date} · {report.pages}
            </p>

            <div className="flex items-center justify-between pt-3 border-t border-white/5">
              <span className="text-[11px] text-indigo-300 font-medium">{report.department}</span>
              <button
                onClick={() => {
                  toast.success(`Downloaded ${report.title}`);
                }}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/5 hover:bg-white/10 text-white text-xs font-medium transition-colors"
              >
                <Download size={12} />
                Download
              </button>
            </div>
          </GlowCard>
        ))}
      </div>
    </div>
  );
}
